create table teams.person (date_creation bigint, date_modification bigint, person_id bigserial not null, email varchar(255), name varchar(255), surname varchar(255), primary key (person_id));
create table teams.pivot_task_person (person_id bigint not null, task_id bigint not null);
create table teams.state (state_id bigserial not null, name varchar(255), primary key (state_id));
create table teams.tag (tag_id bigserial not null, name varchar(255), primary key (tag_id));
create table teams.task (date_creation bigint, date_echeance bigint, date_modification bigint, person_id bigint, task_id bigserial not null, description varchar(255), title varchar(255), notes varchar(255) array, primary key (task_id));
alter table if exists teams.pivot_task_person add constraint FKf401qb7j06229a8ndyrx7k6xv foreign key (person_id) references teams.person;
alter table if exists teams.pivot_task_person add constraint FK6seimrx9ae48sj4cnvjh41gf foreign key (task_id) references teams.task;
alter table if exists teams.task add constraint FK1b9x9tb4qrlrhnb6v2xes2792 foreign key (person_id) references teams.person;
create table teams.person (date_creation bigint, date_modification bigint, person_id bigserial not null, email varchar(255), name varchar(255), surname varchar(255), primary key (person_id));
create table teams.pivot_task_person (person_id bigint not null, task_id bigint not null);
create table teams.state (state_id bigserial not null, name varchar(255), primary key (state_id));
create table teams.tag (tag_id bigserial not null, name varchar(255), primary key (tag_id));
create table teams.task (date_creation bigint, date_echeance bigint, date_modification bigint, person_id bigint, task_id bigserial not null, description varchar(255), title varchar(255), notes varchar(255) array, primary key (task_id));
alter table if exists teams.pivot_task_person add constraint FKf401qb7j06229a8ndyrx7k6xv foreign key (person_id) references teams.person;
alter table if exists teams.pivot_task_person add constraint FK6seimrx9ae48sj4cnvjh41gf foreign key (task_id) references teams.task;
alter table if exists teams.task add constraint FK1b9x9tb4qrlrhnb6v2xes2792 foreign key (person_id) references teams.person;
create table teams.person (date_creation bigint, date_modification bigint, person_id bigserial not null, email varchar(255), name varchar(255), surname varchar(255), primary key (person_id));
create table teams.pivot_task_person (person_id bigint not null, task_id bigint not null);
create table teams.state (state_id bigserial not null, name varchar(255), primary key (state_id));
create table teams.tag (tag_id bigserial not null, name varchar(255), primary key (tag_id));
create table teams.task (date_creation bigint, date_echeance bigint, date_modification bigint, person_id bigint, task_id bigserial not null, description varchar(255), title varchar(255), notes varchar(255) array, primary key (task_id));
alter table if exists teams.pivot_task_person add constraint FKf401qb7j06229a8ndyrx7k6xv foreign key (person_id) references teams.person;
alter table if exists teams.pivot_task_person add constraint FK6seimrx9ae48sj4cnvjh41gf foreign key (task_id) references teams.task;
alter table if exists teams.task add constraint FK1b9x9tb4qrlrhnb6v2xes2792 foreign key (person_id) references teams.person;
create table teams.person (date_creation bigint, date_modification bigint, person_id bigserial not null, email varchar(255), name varchar(255), surname varchar(255), primary key (person_id));
create table teams.pivot_task_person (person_id bigint not null, task_id bigint not null);
create table teams.state (state_id bigserial not null, name varchar(255), primary key (state_id));
create table teams.tag (tag_id bigserial not null, name varchar(255), primary key (tag_id));
create table teams.task (date_creation bigint, date_echeance bigint, date_modification bigint, person_id bigint, task_id bigserial not null, description varchar(255), title varchar(255), notes varchar(255) array, primary key (task_id));
alter table if exists teams.pivot_task_person add constraint FKf401qb7j06229a8ndyrx7k6xv foreign key (person_id) references teams.person;
alter table if exists teams.pivot_task_person add constraint FK6seimrx9ae48sj4cnvjh41gf foreign key (task_id) references teams.task;
alter table if exists teams.task add constraint FK1b9x9tb4qrlrhnb6v2xes2792 foreign key (person_id) references teams.person;
create table teams.person (date_creation bigint, date_modification bigint, person_id bigserial not null, email varchar(255), name varchar(255), surname varchar(255), primary key (person_id));
create table teams.pivot_task_person (person_id bigint not null, task_id bigint not null);
create table teams.state (state_id bigserial not null, name varchar(255), primary key (state_id));
create table teams.tag (tag_id bigserial not null, name varchar(255), primary key (tag_id));
create table teams.task (date_creation bigint, date_echeance bigint, date_modification bigint, person_id bigint, state_id bigint, task_id bigserial not null, description varchar(255), title varchar(255), notes varchar(255) array, primary key (task_id));
alter table if exists teams.pivot_task_person add constraint FKf401qb7j06229a8ndyrx7k6xv foreign key (person_id) references teams.person;
alter table if exists teams.pivot_task_person add constraint FK6seimrx9ae48sj4cnvjh41gf foreign key (task_id) references teams.task;
alter table if exists teams.task add constraint FK1b9x9tb4qrlrhnb6v2xes2792 foreign key (person_id) references teams.person;
alter table if exists teams.task add constraint FKpk5d4or4nk6sijctxt0edufrk foreign key (state_id) references teams.state;
create table teams.note (bool boolean not null, note_id bigserial not null, task_id bigint, name varchar(255), primary key (note_id));
create table teams.person (date_creation bigint, date_modification bigint, person_id bigserial not null, email varchar(255), name varchar(255), surname varchar(255), primary key (person_id));
create table teams.pivot_task_person (person_id bigint not null, task_id bigint not null);
create table teams.state (state_id bigserial not null, name varchar(255), primary key (state_id));
create table teams.tag (tag_id bigserial not null, name varchar(255), primary key (tag_id));
create table teams.task (date_creation bigint, date_echeance bigint, date_modification bigint, person_id bigint, state_id bigint, task_id bigserial not null, description varchar(255), title varchar(255), primary key (task_id));
alter table if exists teams.note add constraint FKd5ne8aaau1mrrf9e6glg6sfe0 foreign key (task_id) references teams.task;
alter table if exists teams.pivot_task_person add constraint FKf401qb7j06229a8ndyrx7k6xv foreign key (person_id) references teams.person;
alter table if exists teams.pivot_task_person add constraint FK6seimrx9ae48sj4cnvjh41gf foreign key (task_id) references teams.task;
alter table if exists teams.task add constraint FK1b9x9tb4qrlrhnb6v2xes2792 foreign key (person_id) references teams.person;
alter table if exists teams.task add constraint FKpk5d4or4nk6sijctxt0edufrk foreign key (state_id) references teams.state;
create table teams.note (bool boolean not null, note_id bigserial not null, task_id bigint, name varchar(255), primary key (note_id));
create table teams.person (date_creation bigint, date_modification bigint, person_id bigserial not null, email varchar(255), name varchar(255), surname varchar(255), primary key (person_id));
create table teams.pivot_task_person (person_id bigint not null, task_id bigint not null);
create table teams.state (state_id bigserial not null, name varchar(255), primary key (state_id));
create table teams.tag (tag_id bigserial not null, name varchar(255), primary key (tag_id));
create table teams.task (date_creation bigint, date_echeance bigint, date_modification bigint, person_id bigint, state_id bigint, task_id bigserial not null, description varchar(255), title varchar(255), primary key (task_id));
alter table if exists teams.note add constraint FKd5ne8aaau1mrrf9e6glg6sfe0 foreign key (task_id) references teams.task;
alter table if exists teams.pivot_task_person add constraint FKf401qb7j06229a8ndyrx7k6xv foreign key (person_id) references teams.person;
alter table if exists teams.pivot_task_person add constraint FK6seimrx9ae48sj4cnvjh41gf foreign key (task_id) references teams.task;
alter table if exists teams.task add constraint FK1b9x9tb4qrlrhnb6v2xes2792 foreign key (person_id) references teams.person;
alter table if exists teams.task add constraint FKpk5d4or4nk6sijctxt0edufrk foreign key (state_id) references teams.state;
create table teams.note (bool boolean not null, note_id bigserial not null, task_id bigint, name varchar(255), primary key (note_id));
create table teams.person (date_creation bigint, date_modification bigint, person_id bigserial not null, email varchar(255), name varchar(255), surname varchar(255), primary key (person_id));
create table teams.pivot_task_person (person_id bigint not null, task_id bigint not null);
create table teams.state (state_id bigserial not null, name varchar(255), primary key (state_id));
create table teams.tag (tag_id bigserial not null, name varchar(255), primary key (tag_id));
create table teams.task (date_creation bigint, date_echeance bigint, date_modification bigint, person_id bigint, state_id bigint, task_id bigserial not null, description varchar(255), title varchar(255), primary key (task_id));
alter table if exists teams.note add constraint FKd5ne8aaau1mrrf9e6glg6sfe0 foreign key (task_id) references teams.task;
alter table if exists teams.pivot_task_person add constraint FKf401qb7j06229a8ndyrx7k6xv foreign key (person_id) references teams.person;
alter table if exists teams.pivot_task_person add constraint FK6seimrx9ae48sj4cnvjh41gf foreign key (task_id) references teams.task;
alter table if exists teams.task add constraint FK1b9x9tb4qrlrhnb6v2xes2792 foreign key (person_id) references teams.person;
alter table if exists teams.task add constraint FKpk5d4or4nk6sijctxt0edufrk foreign key (state_id) references teams.state;
create table teams.note (bool boolean not null, note_id bigserial not null, task_id bigint, name varchar(255), primary key (note_id));
create table teams.person (date_creation bigint, date_modification bigint, person_id bigserial not null, email varchar(255), name varchar(255), surname varchar(255), primary key (person_id));
create table teams.pivot_task_person (person_id bigint not null, task_id bigint not null);
create table teams.state (state_id bigserial not null, name varchar(255), primary key (state_id));
create table teams.tag (tag_id bigserial not null, name varchar(255), primary key (tag_id));
create table teams.task (date_creation bigint, date_echeance bigint, date_modification bigint, person_id bigint, state_id bigint, task_id bigserial not null, description varchar(255), title varchar(255), primary key (task_id));
alter table if exists teams.note add constraint FKd5ne8aaau1mrrf9e6glg6sfe0 foreign key (task_id) references teams.task;
alter table if exists teams.pivot_task_person add constraint FKf401qb7j06229a8ndyrx7k6xv foreign key (person_id) references teams.person;
alter table if exists teams.pivot_task_person add constraint FK6seimrx9ae48sj4cnvjh41gf foreign key (task_id) references teams.task;
alter table if exists teams.task add constraint FK1b9x9tb4qrlrhnb6v2xes2792 foreign key (person_id) references teams.person;
alter table if exists teams.task add constraint FKpk5d4or4nk6sijctxt0edufrk foreign key (state_id) references teams.state;
create table teams.note (bool boolean not null, note_id bigserial not null, task_id bigint, name varchar(255), primary key (note_id));
create table teams.person (date_creation bigint, date_modification bigint, person_id bigserial not null, email varchar(255), name varchar(255), surname varchar(255), primary key (person_id));
create table teams.pivot_task_person (person_id bigint not null, task_id bigint not null);
create table teams.state (state_id bigserial not null, name varchar(255), primary key (state_id));
create table teams.tag (tag_id bigserial not null, name varchar(255), primary key (tag_id));
create table teams.task (date_creation bigint, date_echeance bigint, date_modification bigint, person_id bigint, state_id bigint, task_id bigserial not null, description varchar(255), title varchar(255), primary key (task_id));
alter table if exists teams.note add constraint FKd5ne8aaau1mrrf9e6glg6sfe0 foreign key (task_id) references teams.task;
alter table if exists teams.pivot_task_person add constraint FKf401qb7j06229a8ndyrx7k6xv foreign key (person_id) references teams.person;
alter table if exists teams.pivot_task_person add constraint FK6seimrx9ae48sj4cnvjh41gf foreign key (task_id) references teams.task;
alter table if exists teams.task add constraint FK1b9x9tb4qrlrhnb6v2xes2792 foreign key (person_id) references teams.person;
alter table if exists teams.task add constraint FKpk5d4or4nk6sijctxt0edufrk foreign key (state_id) references teams.state;
